import { Decision } from "../CaseSearchPage";

export const MOCK_DECISIONS: Decision[] = [
  {
    id: "1",
    title: "Yargıtay 11. Hukuk Dairesi 2023/4567 E., 2024/1234 K.",
    court: "Yargıtay",
    country: "Turkey",
    date: "2024-03-15",
    summary: "Tahliye davasında, kiracının taşınmazda bulunması nedeniyle yapılamayan tadilat işlemlerinin, kira sözleşmesinin feshi için haklı sebep oluşturduğu ve tahliye talebinin kabulüne karar verilmiştir.",
    keywords: ["Tahliye Davası", "Kira Hukuku", "Tadilat", "Fesih"],
    fullText: "Mahkemece yapılan keşif ve bilirkişi incelemesi neticesinde, davalı kiracının taşınmazda bulunmasıyla tadilat işlemlerinin yapılamayacağı tespit edilmiş olup, bu durumun kira sözleşmesinin feshi için haklı sebep oluşturduğu sonucuna varılmıştır. TMK'nun ilgili maddeleri uyarınca, kiracının sözleşmeden kaynaklanan yükümlülüklerini yerine getirmemesi durumunda kira sözleşmesi haklı sebeple feshedilebilir. Bu nedenle davacı mal sahibinin tahliye talebinin kabulüne karar verilmiştir.",
  },
  {
    id: "2",
    title: "Yargıtay 19. Hukuk Dairesi 2023/8912 E., 2024/456 K.",
    court: "Yargıtay",
    country: "Turkey",
    date: "2024-02-20",
    summary: "Haksız rekabet davasında, davalının piyasa değerinin altında satış yaparak haksız rekabet oluşturduğu ve bundan vazgeçmesine karar verilmiştir. TTK m.55 kapsamında değerlendirilmiştir.",
    keywords: ["Haksız Rekabet", "Ticaret Hukuku", "Rekabet", "TTK"],
    fullText: "Davalının, piyasa değerinin altındaki fiyatlarla ürün satarak haksız rekabete yol açtığı iddiasıyla açılan davada, mahkemece davalının bu davranışının TTK m.55 kapsamında haksız rekabet oluşturduğu ve bundan vazgeçmesine karar verilmiştir. TTK'nun haksız rekabet hükümleri, ticari hayatta dürüstlük kuralına aykırı davranışları yasaklamaktadır. Piyasa değerinin altında satış yaparak rakipleri zor duruma düşürmek, haksız rekabet teşkil eder.",
  },
  {
    id: "3",
    title: "Yargıtay 2. Hukuk Dairesi 2023/3456 E., 2024/789 K.",
    court: "Yargıtay",
    country: "Turkey",
    date: "2024-01-10",
    summary: "İşçi tazminat davasında, işverenin işçiyi haklı nedenle fesih hakkını kötüye kullandığı ve tazminat ödemesine karar verilmiştir. İş Kanunu m.17 uygulanmıştır.",
    keywords: ["İş Hukuku", "Haklı Fesih", "Tazminat", "İşçi"],
    fullText: "Davacı işçinin, işveren tarafından haklı nedenle iş sözleşmesinin feshedildiği iddiasına karşı açtığı tazminat davasında, mahkemece işverenin fesih hakkını kötüye kullandığı ve davacının haklı nedenle fesih tazminatına hak kazandığı sonucuna varılmıştır. İş Kanunu'nun 17. maddesi uyarınca, işverenin fesih hakkını objektif ve makul nedenler olmadan kullanması durumunda işçi tazminat talep edebilir.",
  },
  {
    id: "4",
    title: "Yargıtay 4. Hukuk Dairesi 2023/5678 E., 2024/234 K.",
    court: "Yargıtay",
    country: "Turkey",
    date: "2024-04-05",
    summary: "Tüketici davasında, ürünün ayıplı olması nedeniyle tüketicinin cayma hakkını kullandığı ve ödemenin iadesine karar verilmiştir. Tüketicinin Korunması Hakkında Kanun uygulanmıştır.",
    keywords: ["Tüketici Hukuku", "Ayıplı Ürün", "Cayma Hakkı", "İade"],
    fullText: "Davacı tüketicinin, satın aldığı ürünün ayıplı olduğunu iddia ederek açtığı davada, mahkemece ürünün gerçekten ayıplı olduğu ve tüketicinin Tüketicinin Korunması Hakkında Kanun uyarınca cayma hakkını kullanabileceği sonucuna varılmıştır. Ayıplı ürünlerde tüketici, ürünü geri vererek ödemenin iadesini talep edebilir.",
  },
  {
    id: "5",
    title: "Yargıtay 5. Hukuk Dairesi 2023/9012 E., 2024/567 K.",
    court: "Yargıtay",
    country: "Turkey",
    date: "2024-03-28",
    summary: "Borçlar hukuku davasında, sözleşmeden doğan alacağın ödenmesi talebi kabul edilmiş ve faiz hüküm kurulmuştur. Borçlar Kanunu m.88 uygulanmıştır.",
    keywords: ["Borçlar Hukuku", "Alacak", "Faiz", "Sözleşme"],
    fullText: "Davacının, sözleşmeden kaynaklanan alacağının ödenmesi talebiyle açtığı davada, mahkemece sözleşmenin geçerli olduğu ve davacının alacak hakkının bulunduğu sonucuna varılmıştır. Borçlar Kanunu'nun 88. maddesi uyarınca, alacağın vadesinden itibaren yasal faiz uygulanmasına karar verilmiştir.",
  },
  {
    id: "6",
    title: "Yargıtay 6. Hukuk Dairesi 2023/3456 E., 2024/890 K.",
    court: "Yargıtay",
    country: "Turkey",
    date: "2024-02-14",
    summary: "Aile hukuku davasında, boşanma nedeni olarak şiddet gösterilmiş ve maddi-manevi tazminat talebi kabul edilmiştir. Türk Medeni Kanunu m.161 uygulanmıştır.",
    keywords: ["Aile Hukuku", "Boşanma", "Şiddet", "Tazminat"],
    fullText: "Davacı eşin, eşinden gördüğü şiddet nedeniyle açtığı boşanma ve tazminat davasında, mahkemece şiddet olaylarının gerçekleştiği ve boşanma nedeninin varlığı tespit edilmiştir. TMK'nun 161. maddesi uyarınca, eşlerden birinin ağır kusuru nedeniyle açılan boşanma davasında diğer eş tazminat talep edebilir.",
  },
  {
    id: "7",
    title: "Yargıtay 7. Hukuk Dairesi 2023/7890 E., 2024/123 K.",
    court: "Yargıtay",
    country: "Turkey",
    date: "2024-01-30",
    summary: "Miras hukuku davasında, mirasçılar arasındaki paylaşım anlaşmazlığı çözülmüş ve miras paylaşımına karar verilmiştir. Türk Medeni Kanunu m.598 uygulanmıştır.",
    keywords: ["Miras Hukuku", "Mirasçı", "Paylaşım", "Tereke"],
    fullText: "Mirasçılar arasındaki miras paylaşım anlaşmazlığına dair açılan davada, mahkemece mirasçıların hak paylarının belirlenmesi ve terekenin paylaşımına karar verilmiştir. TMK'nun 598. maddesi uyarınca, mirasçılar arasında anlaşma sağlanamaması durumunda mahkeme paylaşım yapabilir.",
  },
  {
    id: "8",
    title: "Yargıtay 8. Hukuk Dairesi 2023/2468 E., 2024/456 K.",
    court: "Yargıtay",
    country: "Turkey",
    date: "2024-04-12",
    summary: "Eşya hukuku davasında, taşınmazın tapu iptal ve tescil davası kabul edilmiş ve mülkiyetin davacıya ait olduğu tespit edilmiştir. Türk Medeni Kanunu m.704 uygulanmıştır.",
    keywords: ["Eşya Hukuku", "Tapu İptal", "Tescil", "Mülkiyet"],
    fullText: "Davacının, taşınmazın tapu iptal ve tescil davasında, mahkemece davacının mülkiyet hakkının mevcut olduğu ve tapu kaydının iptal edilerek davacı adına tescil edilmesine karar verilmiştir. TMK'nun 704. maddesi uyarınca, tapu kaydı gerçek durumu yansıtmıyorsa iptal ve tescil davası açılabilir.",
  },
  {
    id: "9",
    title: "Yargıtay 9. Hukuk Dairesi 2023/1357 E., 2024/789 K.",
    court: "Yargıtay",
    country: "Turkey",
    date: "2024-03-22",
    summary: "İcra ve iflas hukuku davasında, alacaklının icra takibinin itiraz üzerine durdurulması talebi reddedilmiş ve icra takibinin devamına karar verilmiştir. İİK m.67 uygulanmıştır.",
    keywords: ["İcra ve İflas", "İcra Takibi", "İtiraz", "Alacak"],
    fullText: "Borçlunun, icra takibine yönelik itirazı üzerine icra takibinin durdurulması talebiyle açılan davada, mahkemece itirazın hukuki dayanağının bulunmadığı ve icra takibinin devam etmesine karar verilmiştir. İİK'nun 67. maddesi uyarınca, itirazın geçerli olması için hukuki bir dayanağının bulunması gerekir.",
  },
  {
    id: "10",
    title: "Yargıtay 10. Hukuk Dairesi 2023/9876 E., 2024/321 K.",
    court: "Yargıtay",
    country: "Turkey",
    date: "2024-02-08",
    summary: "Fikri mülkiyet hukuku davasında, telif hakkı ihlali tespit edilmiş ve ihlalden vazgeçme ve tazminat talebi kabul edilmiştir. FSEK m.71 uygulanmıştır.",
    keywords: ["Fikri Mülkiyet", "Telif Hakkı", "İhlal", "Tazminat"],
    fullText: "Davacının, telif hakkı ihlali iddiasıyla açtığı davada, mahkemece davalının eseri izinsiz kullandığı ve telif hakkı ihlali gerçekleştirdiği sonucuna varılmıştır. FSEK'nun 71. maddesi uyarınca, telif hakkı ihlali durumunda ihlalden vazgeçme ve tazminat talebi kabul edilir.",
  },
];

